#print("Hello World!")
#print("Hello Again")
#print("I like typing like this.")
#print("this is fun.")
#print('Yay! Printing.')
#print("I'd much rather you 'not'.")
print('i "said"do not touch this.')
